name: mathblogging.org cronjob

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - shell: bash
        env:
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          consumer_secret: ${{ secrets.CONSUMER_SECRET }}
          access_token: ${{ secrets.ACCESS_TOKEN}}
          access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET}}
          my_secret: ${{ secrets.TEST_SECRET}}
        run: |
          echo Regenerate mathblogging.org
          echo configure git
          echo "$my_secret"
          git config user.name github-actions
          git config user.email github-actions@github.com
          mbdir=$(pwd)
          echo install mathblogging-base
          npm i mathblogging/mathblogging-base
          echo run build
          cd ./node_modules/mathblogging-base/
          consumer_key=$consumer_key consumer_secret=$consumer_secret access_token=$access_token access_token_secret=$access_token_secret sh ./bin/ci.sh $mbdir
          cd $mbdir
          git add .
          git commit -m "chore: cron job" || true
          git push
