name: mathblogging.org cronjob

on:
  schedule:
    - cron: '17 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - shell: bash
        run: |
          echo Regenerate mathblogging.org
          echo configure git
          git config user.name github-actions
          git config user.email github-actions@github.com
          mbdir=$(pwd)
          echo install mathblogging-base
          npm i mathblogging/mathblogging-base
          echo run build
          cd ./node_modules/mathblogging-base/
          sh ./bin/ci.sh $mbdir
          cd $mbdir
          git add .
          git commit -m "chore: cron job" || true
          git push
